### ISSUE TITLE
add a command line for changing the default location of templates/ directory

### ISSUE THREAD

**Issue by tfarina** [joelweinberger/personal-website#7]
Adding a  --templates-dir flag would let one to tell the go binary where to look for the templates/ directory. Otherwise, the templates/ directory needs to be placed in the same directory as the binary.

**Comment by joelweinberger** [comment]
This has been added in 855fbbc70755b0061050bb9a3a243348ecde27bc.

**Comment by tfarina** [comment]
This is awesome Joel. Thank you!

**Comment by joelweinberger** [comment]
np!
